### ISSUE TITLE
TestIO::test_query_ttyname fails on Jenkins + CentOS

### ISSUE THREAD

**Issue by yorickpeterse** [rubinius/rubinius#2564]
When running the Rubinius test suite (using `rake travis`) on a Jenkins instance running on CentOS yields the following error:

```
Suite TestIO
  test_create: ok
  test_allocate: ok
  test_ensure_open: ok
  test_set_mode: ok
  test_force_read_only: ok
  test_force_write_only: ok
  test_write: ok
  test_query: ok
  test_query_tty: ok
  test_query_ttyname: 
In TestIO::test_query_ttyname:
vm/test/test_io.hpp:116: Error: Test failed: Exception thrown from test
FAIL
  test_create_buffer: ok
```

This is the only test failing but prevents the building of Rubinius on this machine. As far as I know Jenkins does not run tests under a TTY so that might be causing the test to fail. This occurs on Rubinius master.

Output of `uname`: `Linux ip-10-249-62-98 3.4.57-48.42.amzn1.x86_64 #1 SMP Mon Aug 12 21:43:36 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux`.
