### ISSUE TITLE
Including Nokogiri under RSpec crashes (when using Bundler)

### ISSUE THREAD

**Issue by Mange** [rubinius/rubinius#2719]
Simples test case that causes the failure:

```
echo "require 'nokogiri'" > foo_spec.rb
echo "gem 'nokogiri'; gem 'rspec'" > Gemfile && bundle install

bundle exec rspec foo_spec.rb # FAILS
rspec foo_spec.rb # SUCCEEDS
```

Stack trace and error:

```
An exception occurred running at_exit handlers

    no such file to load -- racc/parser.rb (LoadError)

Backtrace:

                    Rubinius::CodeLoader#load_error at kernel/common/code_loader.rb:439
          Rubinius::CodeLoader#resolve_require_path at kernel/common/code_loader.rb:423
                { } in Rubinius::CodeLoader#require at kernel/common/code_loader.rb:103
                               Rubinius.synchronize at kernel/bootstrap/rubinius.rb:137
                       Rubinius::CodeLoader#require at kernel/common/code_loader.rb:102
                       Rubinius::CodeLoader.require at kernel/common/code_loader.rb:237
                             Kernel(Object)#require at kernel/common/kernel.rb:685
                                 Object#__script__ at /Users/mange/.rvm/gems/rbx-2.1.1/gems/nokogiri-1.6.0/lib/nokogiri/css/parser.rb:7
                       Rubinius::CodeLoader.require at kernel/common/code_loader.rb:243
                             Kernel(Object)#require at kernel/common/kernel.rb:685
                                  Object#__script__ at /Users/mange/.rvm/gems/rbx-2.1.1/gems/nokogiri-1.6.0/lib/nokogiri/css.rb:5
                       Rubinius::CodeLoader.require at kernel/common/code_loader.rb:243
                             Kernel(Object)#require at kernel/common/kernel.rb:685
                                  Object#__script__ at /Users/mange/.rvm/gems/rbx-2.1.1/gems/nokogiri-1.6.0/lib/nokogiri.rb:35
                       Rubinius::CodeLoader.require at kernel/common/code_loader.rb:243
                             Kernel(Object)#require at kernel/common/kernel.rb:685
                                  Object#__script__ at foo_spec.rb:1
            Kernel(RSpec::Core::Configuration)#load at kernel/common/kernel.rb:427
 { } in RSpec::Core::Configuration#load_spec_files at /Users/mange/.rvm/gems/rbx-2.1.1/gems/rspec-core-2.14.6/lib/rspec/core
                                                      /configuration.rb:896
                                         Array#each at kernel/bootstrap/array.rb:66
        RSpec::Core::Configuration#load_spec_files at /Users/mange/.rvm/gems/rbx-2.1.1/gems/rspec-core-2.14.6/lib/rspec/core
                                                      /configuration.rb:896
                      RSpec::Core::CommandLine#run at /Users/mange/.rvm/gems/rbx-2.1.1/gems/rspec-core-2.14.6/lib/rspec/core
                                                      /command_line.rb:22
                           RSpec::Core::Runner.run at /Users/mange/.rvm/gems/rbx-2.1.1/gems/rspec-core-2.14.6/lib/rspec/core
                                                      /runner.rb:80
                { } in RSpec::Core::Runner.autorun at /Users/mange/.rvm/gems/rbx-2.1.1/gems/rspec-core-2.14.6/lib/rspec/core
                                                      /runner.rb:17
                                          Proc#call at kernel/bootstrap/proc.rb:20
                      Rubinius::Loader#run_at_exits at kernel/loader.rb:712
                          Rubinius::Loader#epilogue at kernel/loader.rb:732
                              Rubinius::Loader#main at kernel/loader.rb:868
```

**Versions**
- rubinius 2.1.1 (2.1.0 be67ed17 2013-10-18 JI) [x86_64-darwin12.5.0]
- Darwin Lil
  ith.local 12.5.0 Darwin Kernel Version 12.5.0: Mon Jul 29 16:33:49 PDT 2013; root:xnu-2050.48.11~1/RELEASE_X86_64 x86_64 i386 iMac11,3 Darwin
- rvm 1.23.10 (latest)
- `rubysl` 2.0.10
- Bundler version 1.3.5
- RSpec 2.14.1

Nokogiri (1.6.0)

``` yaml
    ---
    warnings: []
    nokogiri: 1.6.0
    ruby:
      version: 2.1.0
      platform: x86_64-darwin12.5.0
      description: rubinius 2.1.1 (2.1.0 be67ed17 2013-10-18 JI) [x86_64-darwin12.5.0]
      engine: rbx
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/Users/mange/.rvm/gems/rbx-2.1.1/gems/nokogiri-1.6.0/ports/i686-apple-darwin11/libxml2/2.8.0"
      libxslt_path: "/Users/mange/.rvm/gems/rbx-2.1.1/gems/nokogiri-1.6.0/ports/i686-apple-darwin11/libxslt/1.1.26"
      compiled: 2.8.0
      loaded: 2.8.0
```
