### ISSUE TITLE
Bundler fails to detect Gems installed using --deployment flag

### ISSUE THREAD

**Issue by YorickPeterse** [rubinius/rubinius#3284]
When installing Gems from a Gemfile using `bundle install --deployment` followed command executions using `bundle exec` result in Bundler complaining that it can't find the installed Gems.

Repro: https://gist.github.com/YorickPeterse/8d088fbf89834057ac91

Download the files in some directory and run the following commands:

    gem uninstall oga # if you have Oga installed globally
    bundle install --deployment
    bundle exec ruby test.rb

This will fail with the following error:

```
Could not find oga-0.2.0 in any of the sources
Run `bundle install` to install missing gems.
```

Contents of `.bundle/config`:

```
--- !ruby/hash-with-ivars
elements:
  BUNDLE_FROZEN: '1'
  BUNDLE_PATH: vendor/bundle
  BUNDLE_DISABLE_SHARED_GEMS: '1'
ivars:
  :@mask: 15
  :@entries: !ruby/object:Rubinius::Tuple {}
  :@capacity: 16
  :@max_entries: 12
  :@state: &1 !ruby/object:Hash::State
    compare_by_identity: false
    head: &3 !ruby/object:Hash::Bucket
      value: '1'
      next: &2 !ruby/object:Hash::Bucket
        value: vendor/bundle
        next: &4 !ruby/object:Hash::Bucket
          value: '1'
          key: BUNDLE_DISABLE_SHARED_GEMS
          key_hash: 131425715903379991
          link: 
          state: *1
          previous: *2
        key: BUNDLE_PATH
        key_hash: 4298503715789598448
        link: 
        state: *1
        previous: *3
      key: BUNDLE_FROZEN
      key_hash: 405838037720555079
      link: *4
      state: *1
    tail: *4
  :@size: 3
```
