### ISSUE TITLE
/Users/travis/.rvm/rubies/rbx//library/rbconfig.rb: No such file or directory

### ISSUE THREAD

**Issue by medols** [rubinius/rubinius#3624]
## Problem

rbx-3.16:

Travis fails to import gemset /Users/travis/.rvm/gemsets/global.gems on osx but succeeds on linux.
Due to "/Users/travis/.rvm/rubies/rbx//library/rbconfig.rb: No such file or directory".

## How to Reproduce

```
  language: ruby
  rvm:
  - rbx

  os:
  - linux
  - osx
```

## Configuration Details

Configuration details and stack traces for osx and linux:

https://travis-ci.org/medols/fresh/builds/112220847
