### ISSUE TITLE
String#sub not allocating a new string

### ISSUE THREAD

**Issue by brauliobo** [rubinius/rubinius#3633]
Create a spec file with contents:
```ruby
def suffix_url url                                                                                                                                                                           
  url = url.sub /\/suffix.*$/, ''                                                                                                                                                            
  url << '/suffix?sortOrder=newest'                                                                                                                                                          
end                                                                                                                                                                                          
                                                                                                                                                                                             
describe '#suffix_url' do                                                                                                                                                                    
  it 'add /suffix with parameters to the url' do                                                                                                                                             
    url = 'http://www.example.com/site'                                                                                                                                                      
    expect(suffix_url url).to eq "#{url}/suffix?sortOrder=newest"                                                                                                          
                                                                                                                                                                                             
    url = 'http://www.example.com/site/suffix'                                                                                                                                               
    expect(suffix_url url).to eq "#{url}?sortOrder=newest"                                                                                                                 
  end                                                                                                                                                                                        
end                                                                                                                                                                                          
```

Running it will fail with:
```
~/P/o/test git:master ❯❯❯ be rspec bug_spec.rb                                                                                                                                 ⏎
F

Failures:
  1) #suffix_url add /suffix with parameters to the url
     Failure/Error: expect(@collector.send :suffix_url, url).to eq "#{url}/suffix?sortOrder=newest"
       
       expected: "http://www.example.com/site/suffix?sortOrder=newest/suffix?sortOrder=newest"
            got: "http://www.example.com/site/suffix?sortOrder=newest"
       
       (compared using ==)
     # ./bug_spec.rb:10:in `__script__'
     # core/basic_object.rb:176:in `instance_exec'
     # core/array.rb:93:in `map'
     # core/array.rb:93:in `map'
     # core/kernel.rb:588:in `load'
     # core/code_loader.rb:505:in `load_script'
```

Tested on rbx 2.5.2 and 3.22, works with MRI
