### ISSUE TITLE
Rubinius fails to build on Ubuntu 18.04 in GitHub Actions

### ISSUE THREAD

**Issue by eregon** [rubinius/rubinius#3828]
1. What command did you run?

  I ran `./build.sh --prefix=~/.rubies/rbx-4.12`
Full output and commands at https://github.com/eregon/ruby-install-builder/runs/380326221

2. What behavior did you expect?

  I expected it builds sucessfully.

3. What behavior did you get instead?

It fails with:
```
...
3: CC machine/util/timing.c
3: CC machine/util/utf8.c
3: CC machine/util/vsnprintf.c
3: CXX machine/vm.cpp
3: CXX machine/vm_thread_state.cpp
Build time: 382.5293304 seconds
1: LD machine/vm
GEN codedb/platform.conf
rake aborted!
Don't know how to build task '' (see --tasks)

Tasks: TOP => default => spec => build => build:build => core:build => codedb:extensions
(See full trace by running task with --trace)
##[error]Process completed with exit code 1.
```

4. What version of Rubinius?

4.12

5. What version of operating system?

Ubuntu 18.04

7. How did you build your version of Rubinius?

  - [x] I built manually from a tarball.
---

It should be easy to run this workflow to reproduce:
```yaml
on: [push]
jobs:
  build:
    if: true
    strategy:
      matrix:
        os: [ ubuntu-18.04 ]
        ruby: [ rbx-4.12 ]
    runs-on: ${{ matrix.os }}
    steps:
    - run: sudo apt-get update
    - run: sudo apt-get install ruby clang llvm

    - run: wget 'https://github.com/rubinius/rubinius/releases/download/v4.12/rubinius-4.12.tar.bz2'
    - run: tar xf rubinius-4.12.tar.bz2
    - run: ./build.sh --prefix=~/.rubies/${{ matrix.ruby }}
      working-directory: rubinius-4.12

    - name: Install Bundler if needed
      run: |
        if [ ! -e ~/.rubies/${{ matrix.ruby }}/bin/bundle ]; then
          export PATH="$HOME/.rubies/${{ matrix.ruby }}/bin:$PATH"
          gem install bundler -v '~> 1' --no-document
        fi
    - name: Basic test
      run: ~/.rubies/${{ matrix.ruby }}/bin/ruby --version
    - name: OpenSSL test
      run: ~/.rubies/${{ matrix.ruby }}/bin/ruby -ropen-uri -e 'puts open("https://rubygems.org/") { |f| f.read(2014) }'
```

Already-built versions for Ubuntu 18.04 might help here, although different system library versions might be problematic.
I noticed there are [builds](http://rubinius-binaries-rubinius-com.s3-us-west-2.amazonaws.com/index.txt) for 16.04 and 14.04 but not for 18.04.
